### ISSUE TITLE
Change Verbiage on Tile in Homekit

### ISSUE THREAD

**Issue by fratinize** [aqualinkd/homebridge-aqualinkd#11]
So I have the Freeze Protect Reading that I uses as a Temp Sensor on my Deck (makes Room "Deck" )Look Complete by Showing Temp). I can Change the Name of the Tile in Homekit (Yard Tempruature), but HomeKit Gives me no way to Change the "cool to" verbiage below Temp. 

Since I am using this Sensor for other than its use (I live in South Florida, if We have Gone Down to Freezing 2 x in the Past 10 Years and my Pump came on that's a Lot) In any Event I'd Like to be able to Change "cool to" Which represents the Temp The Pump Should turn on to Protect it, to Something like "Protect pump at"
Is this Something that Can be done on my local End. Modify a File? On the Aqualinkd Server? Thanx for any Direction

[HK Deck Temp.pdf](https://github.com/sfeakes/homebridge-aqualinkd/files/9569459/HK.Deck.Temp.pdf)

**Comment by sfeakes** [comment]
That’s a limitation of apple homekit, nothing can be done to change the text.  But, the freeze protect is simply a thermostat that get’s the actual temperature from the air temp sensor, which you can also have in homebridge-aqualinkd.  So why don’t you simply use AqualinkD’s Air temp sensor, that way you simply get the temp with no “cool to” message

**Comment by fratinize** [comment]
I do ,that is in the Backyard Room. Like I said It nice to see the temp in each room. I thought that "Cool to" was something you had coded into the plugin or app and it was carried over.
Thanx
