### ISSUE TITLE
AqualinkD 404 error not found

### ISSUE THREAD

**Issue by woodgieboodgie** [aqualinkd/homebridge-aqualinkd#12]
Hi,

I previously got the error that stated that no plugin was installed.  changed the platform to 'aqualinkd' lowercase and now the 404 error has presented itself.

I am also running sprinklerd on the same Pi.  Can the two co-exist?  does anyone have suggestions re how to fix the 404 error?

**Comment by sfeakes** [comment]
sprinklerd and aqualinkd can co-exist on the same machine, but since they both default to port 80 for the web interface, you will nee to change one to another port.  Where are you getting the 404 error, on AqualinkD web interface of HomeKit?
You might fine that sprinklerd has taken port 80 first so aqualinkd can't start.

**Comment by woodgieboodgie** [comment]
Spot on!  That’s exactly what the issue was. Stopped sprinklerd and refreshed browser and aqualinkd came right up. Shall change their ports and make them unique.

However am slightly confused how to program the conf file. Do I run a command to get the config from the controller and then edit the conf file?

Am running RS8 combo

On 12 Dec 2022, at 10:54 am, sfeakes ***@***.***> wrote:

﻿

sprinklerd and aqualinkd can co-exist on the same machine, but since they both default to port 80 for the web interface, you will nee to change one to another port. Where are you getting the 404 error, on AqualinkD web interface of HomeKit?
You might fine that sprinklerd has taken port 80 first so aqualinkd can't start.

**Comment by woodgieboodgie** [comment]
![Screenshot 2022-12-12 170232](https://user-images.githubusercontent.com/52473319/206971647-f9b67f4e-7eb0-404c-8b65-8c652a09eba2.png)

**Comment by sfeakes** [comment]
You need to edit the config files on the machine itself.  You can ssh to the machine and use a test editor like VI.  Or you can use something like FTP to copy the file to a different machine, edit it and copy it back.  Just depends on what you are happy doing.  But there is no UI to either copy or edit the config file.

**Comment by woodgieboodgie** [comment]
[image0.jpeg]

This is our panel. Are you able to assist us programming it into aqualinkd.conf?

On 14 Dec 2022, at 11:27 am, sfeakes ***@***.***> wrote:

﻿

You need to edit the config files on the machine itself. You can ssh to the machine and use a test editor like VI. Or you can use something like FTP to copy the file to a different machine, edit it and copy it back. Just depends on what you are happy doing. But there is no UI to either copy or edit the config file.

**Comment by woodgieboodgie** [comment]
![panel aqualink r8 combo](https://user-images.githubusercontent.com/52473319/207792704-bbf48a38-ad6c-4e7b-aed2-c7060b893d59.jpg)
![Screenshot 2022-12-15 175025](https://user-images.githubusercontent.com/52473319/207792776-5a3dbc86-ceeb-44fd-98af-b2a1c89b89ba.png)
![Screenshot 2022-12-15 174928](https://user-images.githubusercontent.com/52473319/207792789-48a5d1b3-ce78-4d0b-b6f1-4ab0740a4d50.png)


Progress but unfortunately no value for temperature from pool or spa... any hints?
