### ISSUE TITLE
Set up MQTT to report in degF, Homebridge thinks its degC

### ISSUE THREAD

**Issue by agprimatic** [aqualinkd/homebridge-aqualinkd#13]
I have AqualinkD configured to report the temperature in degF (using convert_mqtt_temp_to_c=no).
The plugin thinks the temp is in degC, so it converts it (again) to degF.
Would be nice to either have this communicated between AqualinkD and the plugin, or provide an option to use degF in the plugin.

**Comment by sfeakes** [comment]
[Duplicate to this](https://github.com/sfeakes/AqualinkD/discussions/205)
