### ISSUE TITLE
Some accessories like Heater, Spa Heater go offline after reboot

### ISSUE THREAD

**Issue by woodgieboodgie** [aqualinkd/homebridge-aqualinkd#18]
Hi,

System works fine, then post a reboot some (not all) accessories get rediscovered which renders those already connected 'inaccessible'.

Is there a way to lock accessories so as that a reboot wont detect the need for them to change?

The way to resolve thus far is to stop aqualinkd, then within Homebridge remove the affected accessories one by one and then restart aqualinkd, then reboot homebridge.

**Comment by sfeakes** [comment]
When Aqualinkd starts it doesn’t know everything about the panel, if aqualinkd-homebridge starts too soon it will catch Aqualinkd when it doesn’t know everything about the panel.  So not all devices will be available. Within a few mins all will be back as new devices and old ones deleted.

in AqualkinkD config there are a few options to force aqualinkd into thinking devices are available before it’s found them in the panel.  The are prefixed with “force”
Ie
force_SWG
force_PS_setpoints
force_chem_feeder
