### ISSUE TITLE
Enhancement Question: re Jandy/iAqualink API

### ISSUE THREAD

**Issue by markcsegal** [aqualinkd/homebridge-aqualinkd#3]
Any plan to extend/create a version of this that connects to iaqualink/jandy 's API vs connecting physically to the control board?

**Comment by sfeakes** [comment]
No.  This is for connecting AqualinkD to homebridge.  This doesn't actually connect to the control board, this connected to AqualinkD's API's.

**Comment by markcsegal** [comment]
Sorry I meant connecting this homebridge not to aquilinkd which needs to be connected to the board.. Basically porting this app from home assistant - https://www.home-assistant.io/integrations/iaqualink/.  I am running home assistant just for this one plugin.

**Comment by sfeakes** [comment]
Yup, sorry, using the Jandy cloud API to write back into a local homebridge is not something this project will tackle.  The main point of AqualinkD and homebridge-aqualinkd is to NOT use the Jandy services in any way.

**Comment by markcsegal** [comment]
I know.. was hoping for a new answer.. love Siri control of the devices (easier from the watch in the pool).

**Comment by sfeakes** [comment]
just get a Raspberry Pi zero, USB 2 RS485 adapter and use AqualinkD...:)

**Comment by markcsegal** [comment]
almost did..I even had a spare pi.. then found home assistant... :).
