### ISSUE TITLE
Swg level as temp

### ISSUE THREAD

**Issue by fratinize** [aqualinkd/homebridge-aqualinkd#4]
Is there really no way to change the salt water level to read ppm instead of temp? In hk

**Comment by sfeakes** [comment]
Apple HomeKit does not support PPM.  Only viable sensor was temperature/degrees when I wrote this.  I have not looked at the latest spec's in a about 6 months, but I doubt there is anything better.  If you have any ideas, please feel free to suggest.

**Comment by fratinize** [comment]
How about a % like a lite dimmer

How about the generator itself showing as its %?

Thanx for listening love the work

**Comment by fratinize** [comment]
I am also Getting a ton of Checksums. If I got to the Web UI I see All My Devices, See my Salt Level and Output%, These are all In Home Kit, But my Serial Logging shows Bad Packets, Bad Jandy Check sum (See Below). I Have Confirmed My Wiring is Solid, I tap off My All Button Just the Data + and -. Now I am Running 8158 Rev K. On the Aqualink Box Itself, I have Tapped my Auto Pilot SWG to the Only Red Pin Connector I have.  (Also have Tested With the SWG Not Connected. Same Results.
Thought? TY

pi@raspberrypi:~/software/AqualinkD $ sudo ./release/serial_logger /dev/ttyUSB0
AqualinkD serial_logger V1.4
Notice: RS Serial: Logging serial information!
Please wait.Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x0a of type Probe | HEX: 0x10|0x02|0x0a|0x00|0x00|0x00|0x2e|0x10|0x02|0x08|0x00|0x00|0x2c|0x03|0x10|0x13|0x10|0x10|0x02|0x08|0x00|0x4f|0x4c|0x4d|0x20|0x37|0xdf|0x20|0x10|0x10|0x02|0x01|0x00|0x10|0x10|0x19|0x03|0x11|0xaf|0x03|0x02|0x12|0x00|0x10|0x03|
Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x1a of type Unknown '0x2c' | HEX: 0x10|0x02|0x1a|0x2c|0x03|0x11|0xaf|0x03|0x02|0x00|0x12|0x00|0x10|0x10|0x02|0x0a|0x00|0x00|0x00|0x2e|0x10|0x03|
Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x08 of type Probe | HEX: 0x10|0x02|0x08|0x00|0x00|0x00|0x2c|0x00|0x10|0x02|0x00|0x01|0x00|0x00|0x13|0x10|0x03|
Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x20 of type Probe | HEX: 0x10|0x02|0x20|0x00|0x10|0x10|0x02|0x50|0x3c|0xaf|0x10|0x03|
Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x00 of type Unknown '0x12' | HEX: 0x10|0x02|0x00|0x12|0x40|0x00|0x64|0x10|0x10|0x02|0x0a|0x00|0x00|0x00|0x2e|0x03|0x02|0x10|0x10|0x02|0x01|0x00|0x10|0x03|
Warning: RS Serial: Serial read bad Jandy checksum, ignoring
Warning: RS Serial: BAD PACKET To 0x50 of type Unknown '0x3c' | HEX: 0x10|0x02|0x50|0x3c|0x10|0x10|0x02|0x00|0x40|0x64|0x03|0x02|0x10|0x00|0x2e|0x10|0x10|0x02|0x08|0x00|0x00|0x00|0x2c|0x03|0x10|0x13|0x03|0x03|0x20|0x6f|0x6c|0x6c|0x74|0x36|0x25|0xca|0x03|0x00|0x00|0x13|0x03|0x02|0x10|0x10|0x02|0x50|0x3c|0x10|0x10|0x40|0x64|0x10|0x02|0x02|0x00|0x10|0x00|0x00|0x00|0x2e|0x10|0x03|
W

**Comment by sfeakes** [comment]
Checksums are RS485 connection issues.  Read the wiki in AqualinkD.  

in the light %, the issue there is then you’re dealing with a lightbulb icon, and HomeKit expects the light dimmer to be “settable” and PPM is a sensor, that creates another set of issues.  But I just realized that the latest iOS combines all the temp sensors into one, (with no way to separate) which is an absolute disaster.   I’ll spent some time looking for a better option when I get time.

**Comment by fratinize** [comment]
Hello,
So It seems AqualinkD is Functioning have Gotten it to Work in HK. I do not get all the Checksums when I stop AqualinkD. 

My Problem now is this, and please forgive my Ignorance/Noobness, I started connected to Ethernet. During the Serial Challenges, I discovered I could Turn on WiFi on the Pi, with the Thought I would Have to Get The USB2RS485 closer to The Panel.  All of a Sudden the Eth ip would just show the Blue Line at the Top but no Buttons. I shut off the WiFi, still not able to See the Web Page. Looking Further I noticed The Web Server would not start. Tried Netstat, but saw nothing using port 80, changed port in Both files to 81, got same result. Finally Resolved by Uninstalling AqualinkD and Reinstalling. All of a Sudden I had to Use the WiFi Address. (The LAN Ip still shows only the Blue Line)

So With all Function Properly, I wanted to Change the Background pic in the Browser, but it Did not Change. Tried four Different Browsers. (Chrome, Safari and IOS Safari and Chromium) same Results, your Default background. Upon Looking around I see I have 4 Directories in my software folder.

pi@AqualinkPi:~/software $ ls
Aqualinkd  AqualinkD  AqualinkD-2.2.2  AqualinkD-2.2.2a

All Contain The Same Stuff, but the Changes I make to config.js do not show when I inspect in Chrome.

I guess my Question is Why do I have All these directories? And Which one is the One? I am Assuming its The AqualinkD-2.2.2a? Can I delete the Others?

At this Point in time, The Only Browser Working is My iPhone, but not my background I get just a Blue Line on the Chrome and Safari and Chromium browsers.(both Lan and Wifi Address’) HK seems fine, can Turn on and Off and seems to be true to whats running.

My Next Step is To Restart the Pi (as You can Probably tell by the name, it is Dedicated to AqualinkD) but Wanted to Get some Thoughts on my Current Install.

Thank You for your Time

Regards,
Frank

**Comment by fratinize** [comment]
Sorry to fill your email I have resolved the background issue apparently I need to change the configuration in
Var/www/aqualink/hk 
I was under the impression I needed to do the one in software/AqualinD/web

I wound up deleting all aqualink a stuff and started from scratch was quite the learning tans more to go
Thanx again for this program/plug in

Still looking forward to an update to the ppm and % good luck

**Comment by sfeakes** [comment]
There really is no way round this even in latest Homekit / iOS / home bridge.  So leaving as is.
