### ISSUE TITLE
No plugin was found for the platform "AqualinkD" in your config.json. Please make sure the corresponding plugin is installed correctly.

### ISSUE THREAD

**Issue by fratinize** [aqualinkd/homebridge-aqualinkd#9]
Anytime I restart homebridge, I get this Message in the logs. I certainly have a config in my json and Aqualink seems to be functioning correctly. 
Not sure ion there are issue. But I wanted to Point this out.

No plugin was found for the platform "AqualinkD" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by sfeakes** [comment]
can you post your config.json file, as that's not normal.

**Comment by fratinize** [comment]
So As I Mentioned I have Seen this For a few months and Decided to Mention it today. Why? Who Know, but I was a having MQTT issues. My SD card in my PI failed, I had a Very old backup and Needed to Do Some Major Updates...
, In the Process I chased a mqtt issue. Bottom Line, Sorry for the mistake, but Apparently I had a SECOND Aqualink config in my json. :( Sorry About that. I removed and no longer see that message. Hope somebody Learned something :P Than Kyou for the Attention

**Comment by kamaleddin** [comment]
I have the same problem and my config looks fine:
        {
            "name": "aqualinkd",
            "server": "192.168.1.243",
            "port": "80",
            "mqtt": {
                "host": "192.168.1.58",
                "port": "1883",
                "topic": "aqualinkd",
                "username": "mqtt-user",
                "password": "hidden"
            },
            "excludedDevices": [
                "Temperature/Spa",
                "Temperature/Pool",
                "Temperature/Air",
                "SWG/Percent_f"
            ],
            "platform": "AqualinkD"
        }

and here is the error:
No plugin was found for the platform "AqualinkD" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by sfeakes** [comment]
Either you have edited the wrong config or there is an error in it.  This warning is from Homebridge seeing aqualinkd code but not seeing aqualinkd config.

**Comment by kamaleddin** [comment]
I double-checked my config and it was fine. I am getting these warnings when I try to install the package tho:
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by kamaleddin** [comment]
I found the problem. the platform name should have been "aqualinkd" (all lower case) not "AqualinkD"
that solved the problem

**Comment by fratinize** [comment]
It seems the in the UI When We Setup our server, it Makes the platform "AqualinkD"

**Comment by fratinize** [comment]
> So As I Mentioned I have Seen this For a few months and Decided to Mention it today. Why? Who Know, but I was a having MQTT issues. My SD card in my PI failed, I had a Very old backup and Needed to Do Some Major Updates...
> , In the Process I chased a mqtt issue. Bottom Line, Sorry for the mistake, but Apparently I had a SECOND Aqualink config in my json. :( Sorry About that. I removed and no longer see that message. Hope somebody Learned something :P Than Kyou for the Attention

First this Plug in Worked great. Not Shure what Happened today, but I noticed I had 2 Configs in my json. Both Were Exactly the Same Except for the platform one had 'aqualinkd" and one had "AqualinkD". Lower case was the active. I removed the Plug in, restarted home bridge, checked all was good with my home kit and home bridge. All Good.
Reinstalled the AqualinkD plug in, configured. Still Getting this Message
[08/07/2022, 15:51:29] No plugin was found for the platform "AqualinkD" in your config.json. Please make sure the corresponding plugin is installed correctly.

This is the config that was generated through the UI
  {
            "name": "AqualinkD",
            "server": "192.168.1.10",
            "port": "80",
            "mqtt": {
                "host": "192.168.1.10",
                "port": "1883",
                "topic": "aqualinkd"
            },
            "platform": "AqualinkD",
            "_bridge": {
                "username": "0E:1C:CA:23:52:BA",
                "port": 39312
            }
        }
There are of Course no Accessories with this plug in, and If I try to Add to HomeKit, It is not available.

When I change the AqualinkD to aqualinkd in the config (I don't see a way in the UI) we get a default 127.0.0.1 servers in the ui, but still have the proper config we just modified in the json. Still have no accessories, but it is available in HomeKit, but no accessories (Just the Bridge).
If I modify the UI I get a New Bridge
 {
            "name": "AqualinkD",
            "server": "192.168.1.10",
            "port": "80",
            "mqtt": {
                "host": "192.168.1.10",
                "port": "1883",
                "topic": "aqualinkd"
            },
            "platform": "aqualinkd",
            "_bridge": {
                "username": "0E:1C:CA:23:52:BA",
                "port": 39312
            }
        },
        {
            "name": "AqualinkD",
            "server": "192.168.1.10",
            "port": "80",
            "mqtt": {
                "host": "192.168.1.10",
                "port": "1883",
                "topic": "aqualinkd"
            },
            "platform": "AqualinkD",
            "_bridge": {
                "username": "0E:B8:44:55:78:C1",
                "port": 32743
            }
        }

No Accessories and Not Available in HomeKit.

This is the third time I did this in a Row, I can Recreate. I have Rebooted both Servers. My AqualinkD Is running on a pi4 and works just fine if I access it via the Web UI. This Seems to be Isolated to the Plug in. any Ideas That I can Look at. Each time I uninstalled the plug in I restarted the Home Bridge pi4, I have Rebooted the Aqualinkpi at least once.

Thank You for any direction

**Comment by fratinize** [comment]
Wound Up Removing the Extra, rebooted the AqualinkD Pi Then The Homebridge pi and All seems ok....

**Comment by petedavey** [comment]
So making the manual adjustment to the config file changing the "platform": "AqualinkD" section to lowercase fixes the issue where the plugin loads but now it's got a bit of a disconnect from the plugin in the GUI, i.e. if I make any changes to the plugin itself, it creates a new duplicate section in the main config file. This seems to be some sort of bug and makes it hard to configure the plugin via the GUI.

**Comment by johntdyer** [comment]
+1

**Comment by sfeakes** [comment]
The latest version has fixed this.  BUT, due to homebridge-ui auto naming the platform, if you upgrade you will need to manually change it from `"name": "aqualinkd"` back to `"name": "AqualinkD"` in your config.
